name: Build and Package OPKG

on:
  push:
    branches-ignore:
      - 'refs/tags/*'
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'
  release:
    types: [published]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot upx

      - name: Install apk-tools
        run: |
          docker run --rm -v /usr/local/bin:/mnt alpine:edge sh -c "apk add --no-cache apk-tools-static && cp /sbin/apk.static /mnt/apk && chmod +x /mnt/apk"

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./src/frontend/dist

      - name: Build and Package
        run: |
          export $(make _return_export_dynamic_env);
          for config in config/*/*.config; do
            cp "${config}" .config;
            make;
          done

      - name: Fetching file list for artifact
        if: ${{ github.event_name != 'release' }}
        id: create_file_list
        run: |
          echo 'file_list<<EOF' >> $GITHUB_OUTPUT
          find . \( -name "magitrickle_*.ipk" -o -name "magitrickle_*.apk" \) -print >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Upload artifact
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ${{ steps.create_file_list.outputs.file_list }}
          if-no-files-found: error
          compression-level: 0

      - name: Upload asset to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |-
            ./.build/magitrickle_*.ipk
            ./.build/magitrickle_*.apk
          token: ${{ secrets.RELEASE_TOKEN }}
